version: '3.8'
services:
  web:
    build: 
      context: AngularMovie/.
      dockerfile: Dockerfile
    environment:
      API_URL: backend
    ports:
      - 1337:80
    depends_on:
      - backend
  backend:
    build: 
      context : DjangoMovie/.
      dockerfile: Dockerfile
    command: gunicorn djangoProject.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234

    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
  static_volume: