# Generated by Django 3.2.12 on 2022-06-27 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviesdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=200)),
                ('movie_language', models.CharField(max_length=200)),
                ('movie_rating', models.CharField(max_length=200)),
                ('movie_image', models.ImageField(upload_to='media/')),
                ('user_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_added', to='Userauth.users')),
            ],
        ),
    ]
