# Generated by Django 3.2.12 on 2023-02-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdetails',
            name='movie_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
