# Generated by Django 3.2.12 on 2023-02-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviesdetails_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdetails',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
