# Generated by Django 3.2.12 on 2023-03-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230222_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_details',
            name='movie_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_info', to='movies.movies'),
        ),
    ]
