# Generated by Django 3.2.12 on 2023-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='access_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
