# Generated by Django 3.2.12 on 2023-03-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0002_users_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
